site_name: Hu's notebook
theme:
  logo: _assets/icon.png
  favicon: _assets/icon.png
  name: material
  palette:
    primary: cyan
    accent: red
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share

repo_name: zhuhu00/note
repo_url: https://github.com/zhuhu00/note
plugins:
  - search
markdown_extensions:
  - tables
  - pymdownx.betterem
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - mdx_truly_sane_lists # fix typora 2 space indentation, ref: https://github.com/mkdocs/mkdocs/issues/545
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - _js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js