name: ci 
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mdx_truly_sane_lists
      - run: python update_recent.py
      - run: mkdocs gh-deploy --force